### ISSUE TITLE
strange issue

### ISSUE THREAD

**Issue by surfzoid** [bkbilly/Hikvision-Site#4]
hi
i have a strange issie that i missunderstood

the error log (poor)

[Wed Jan 19 15:47:27.591490 2022] [php:error] [pid 731627] [client 127.0.0.1:60716] PHP Fatal error:  Uncaught ImagickException: Failed to read the file in /var/www/html/hik/dispatcher.php:152\nStack trace:\n#0 /var/www/html/hik/dispatcher.php(152): Imagick->__construct()\n#1 /var/www/html/hik/dispatcher.php(25): videopicture()\n#2 {main}\n  thrown in /var/www/html/hik/dispatcher.php on line 152, referer: http://localhost/hik/
[Wed Jan 19 15:47:31.636795 2022] [php:error] [pid 731627] [client 127.0.0.1:60716] PHP Fatal error:  Uncaught ImagickException: Failed to read the file in /var/www/html/hik/dispatcher.php:152\nStack trace:\n#0 /var/www/html/hik/dispatcher.php(152): Imagick->__construct()\n#1 /var/www/html/hik/dispatcher.php(25): videopicture()\n#2 {main}\n  thrown in /var/www/html/hik/dispatcher.php on line 152, referer: http://localhost/hik/

this php file (and other) are owned by apache!

**Comment by bkbilly** [comment]
I am not sure what is going wrong with your setup, but you should make sure you have the correct info on the `.htaccess` file.
 - Make sure that the `camPaths` are pointing to the `info.bin` file.
 - Make sure that you have the correct IPs of the cameras on `camIPs` variable.
 - Lastly make sure the username and password are correct on the `camAuths` variable.

If you are uncertain about the format, send me the file to check it's integrity.

**Comment by bkbilly** [comment]
Looks like you have a different data structure than mine.
I have answered about it on [this](https://github.com/bkbilly/libHikvision/issues/3) issue you created, so we can continue talking about it there.
I am closing this issue for now.
