### ISSUE TITLE
Cannot read properties of undefined (reading 'start') using Prev/Next Event buttons

### ISSUE THREAD

**Issue by raintonr** [bkbilly/Hikvision-Site#6]
After the page has loaded, I see blue marks in the camera timelines indicating events. However, trying to use the Prev/Next Event buttons nothing happens.

Looking in the browser's console these errors appear:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'start')
    at findEvent (myjs.js:189:42)
    at gotoEvent (myjs.js:178:17)
    at document.getElementById.onclick (myjs.js:52:61)
```

**Comment by bkbilly** [comment]
The Next/Prev don't do anything unless you select an event from the blue ones you see on the timeline.
